root: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t khaldountaktak/docker-react .

script:
  - docker run khaldountaktak/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk 
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-813382538170"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
